### ISSUE TITLE
[AC:SLPortable] Booster visual effects don't display for the player

### ISSUE THREAD

**Issue by onionpowder2** [VanLaser/analog-controls-for-armored-core-ps2#2]
In Silent Line Portable, the visual effects for the player's booster do not display with the dual analog patch enabled. The attached picture shows this in action.

Played on PPSSPP 1.16.6

![image](https://github.com/VanLaser/analog-controls-for-armored-core-ps2/assets/108959396/262305be-e1e0-46c2-a5ee-769b872f7083)

**Comment by VanLaser** [comment]
Thanks! Seems to be solved by the PPF patching solution - closing.
