### ISSUE TITLE
[AC LRp] Last Raven .ppf patch side effects

### ISSUE THREAD

**Issue by Victor792019** [VanLaser/analog-controls-for-armored-core-ps2#4]
After some tests, involving AC Test 5, "Defeat Jack-O" mission, and three arena opponents, the purging works as expected, although the patch has the side effects of disabling the "Look Reset" shortcut, even if switching buttons related to the command, and being able to move during the start of missions and arena matches.

Mission done with standard AC performance. Arena matches done with a H+ cheat enabled, and all tests made with Fast Memory enabled in the emulator. AC Test 5 done with both.

Tested with PPSSPP v1.16.6-283 dev build and a 100% save file.
![NPUH10024_00001](https://github.com/VanLaser/analog-controls-for-armored-core-ps2/assets/139256866/e67c9444-49b1-4706-9ddd-20475095a190)
![NPUH10024_00002](https://github.com/VanLaser/analog-controls-for-armored-core-ps2/assets/139256866/55912f08-945d-4275-abf3-6c0436765dc0)
![NPUH10024_00003](https://github.com/VanLaser/analog-controls-for-armored-core-ps2/assets/139256866/5274e641-8c1f-4bf9-be75-d4a7b37d00da)

**Comment by VanLaser** [comment]
Thank you for the nice feedback! I did make some notes about the implementation side-effects - indeed the reset buttons are disabled since all camera buttons are "muted" when the analog axis are enabled. For the analog movement when it shouldn't, I just released an update that fixes that "in most places", but not all (e.g. VR arena still allows the player to move instantly at the very start).

**Comment by VanLaser** [comment]
Another update released, it should fix the look reset shortcut and - in addition - it re-enables support for the "normal" purge method, with all its traditional caveats (for people who can't map the PSP "note" button in the emulator).

**Comment by Victor792019** [comment]
Well, as for me, after patching and booting the .iso the game crashes in every single instance a new map is loaded after the garage (missions, AC Test 5, arena).
Not sure if it's in my end, though i tested with no cheats and H+ cheat on. Also checked Fast Memory on and off, along with ignore bad memory accesses.
Tested with PPSSPP v1.16.6-283 dev build and a 100% save file.
![Captura de tela 2023-12-20 162313](https://github.com/VanLaser/analog-controls-for-armored-core-ps2/assets/139256866/52828401-acbb-4c65-b1ac-a65616750123)
![Captura de tela 2023-12-20 162207](https://github.com/VanLaser/analog-controls-for-armored-core-ps2/assets/139256866/feff4096-5509-48eb-8b8a-4df7d8bc1917)

**Comment by VanLaser** [comment]
I re-did the whole patching procedure as a user would, starting with the PPF file re-downloaded from this location (extracted the "PSP_GAME/SYSDIR/EBOOT.BIN" from the ISO, decrypted the EBOOT.BIN using pspdecrypt, applied the ppf patch with PPF-o-MATIC v3.0, used UMDGen to replace the original EBOOT.BIN in the ISO with the one patched). 

The CRC of the original ISO:  78D272B3. The CRC of the modified ISO becomes: 4EC032B8. 

I tested this with both PPSSPP 1.16.6 (64bit) and PPSSPP 1.13.2 (32bit), fast memory on, ignore illegal read/writes off, and have no crashes in the garage tests, VR arena or when starting missions. Is it possible you either applied the wrong ppf patch, or missed a step in the patching process? (also the CRC being all 0s in your pics is a bit strange, maybe you patched an all 0s EBOOT.BIN like the one from the "PSP_GAME/UPDATE" folder or something like that?)

**Comment by Victor792019** [comment]
Most likely, although I will patch and test it again later.

**Comment by Victor792019** [comment]
So, after patching again, the game works, and while instances of moving before starting missions and matches still are present, like in "Destroy AC Intruder", the "Look Reset" was restored, and the default purging and reset combinations work too.

Tested with PPSSPP v1.16.6-283 dev build and a 100% save file.
![NPUH10024_00004](https://github.com/VanLaser/analog-controls-for-armored-core-ps2/assets/139256866/483f1583-f43e-4960-8cb6-77123e58b821)
![NPUH10024_00005](https://github.com/VanLaser/analog-controls-for-armored-core-ps2/assets/139256866/f9ca2f43-393b-4c2b-8e58-c5ffbdc259e4)

**Comment by VanLaser** [comment]
Thanks again for testing this! This is a relief, since I'm away for a bit from my development setup machine. Also I'll let this issue open for a while, and if nothing else happens I will then close it (and edit the other open issue, so that "early movement" is mentioned all in one place).
