### ISSUE TITLE
Publish Releases

### ISSUE THREAD

**Issue by clach04** [VanLaser/analog-controls-for-armored-core-ps2#8]
As releases are enabled in this GitHub project https://github.com/VanLaser/analog-controls-for-armored-core-ps2/releases any chance releases could be published instead of binary file in the git repo?

Depending on your work flow this may be easier/faster for maintenance as well as downloading.

**Comment by VanLaser** [comment]
Hello, I may do that in the future, after I also release some source code samples. Thanks for the suggestion :)
